<?php
/**
 * The default template part for the product pause_resume in
 * the content-purchases template part's product-info loop
 *
 * @since 1.9.0
 * @version 1.9.0
 * @package exchange-addon-recurring-payments
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange-addon-recurring-payments/lib/templates/content-purchases/elements/ directory
 * located in your theme.
 */
?>

<?php do_action( 'it_exchange_content_purchases_before_product_pause_resume_element' ); ?>
	<div class="it-exchange-item-recurring-payments-pause-resume-payment"><?php it_exchange( 'recurring-payments', 'pause-resume' ); ?></div>
<?php do_action( 'it_exchange_content_purchases_after_product_pause_resume_element' ); ?>