<?php
/**
 * This is the default template for the
 * super-widget-cart recurring_total element.
 *
 * @since 2.0.0
 * @version 2.0.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-cart/elements directory
 * located in your theme.
 */
?>

<?php do_action( 'it_exchange_super_widget_cart_before_recurring_total_element' ); ?>
<div class="cart-recurring-total cart-totals-row" style="font-size: 1em; font-weight: bold">
	<?php do_action( 'it_exchange_super_widget_cart_begin_recurring_total_element' ); ?>
	<?php _e( 'Recurring Total:', 'LION' ); ?> <?php it_exchange( 'cart', 'recurring-total' ); ?>
	<?php do_action( 'it_exchange_super_widget_cart_end_recurring_total_element' ); ?>
</div>
<?php do_action( 'it_exchange_super_widget_cart_after_recurring_total_element' ); ?>
